[features]
seeds = false
skip-lint = false

[programs.mainnet]
goldium_staking = "YourStakingProgramIdHere"

[programs.devnet]
goldium_staking = "YourStakingProgramIdHere"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
